
version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:alpine
    volumes:
      - ./rabbitmq/rabbitmq.confg:/etc/rabbitmq/rabbitmq.config:ro
    restart: always

  mongo-game:
    container_name: mongo-game
    image: mongo
    restart: always

  mongo-round:
    container_name: mongo-round
    image: mongo
    restart: always

  web-service:
    container_name: web-service
    build:
      context: ./NomiCoseCitta
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
     - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq
    restart: always


  game-manager:
    container_name: game-manager
    build:
      context: ./GameManagerService
      dockerfile: Dockerfile 
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGODB=mongodb://mongo-game
    depends_on:
      - rabbitmq
      - mongo-game
    restart: always

  round-manager:
    container_name: round-manager
    build:
      context: ./GameManagerService
      dockerfile: Dockerfile-round
    environment:
      - RABBIT_HOST=rabbitmq
      - MONGODB=mongodb://mongo-round
    depends_on:
      - rabbitmq
      - mongo-round
    restart: always