
version: '3'

services:
  auction-web-service:
    container_name: auction-web-service
    build:
      context: ./auctionWebService
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - PORT=3000
      - MESSAGE_BUS=amqp://rabbitmq
    links:
      - rabbitmq

  user-service:
    container_name: user-service
    build:
      context: ./userService
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - MESSAGE_BUS=amqp://rabbitmq
    links:
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
